export { default as Layout } from './Layout'
export { default as Home } from './Home'
export { default as APropos } from './APropos'
export { default as Projets } from './Projets'
export { default as Contact } from './Contact'
export { default as NotFound } from './NotFound'
